apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ray-pvc-test
  namespace: tianhaowang-ucsd
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: rook-cephfs
  resources:
    requests:
      storage: 1Gi
